;; Leaves: 30-  Connectivity: %5.14285714286 Contradictions: 10
(require '[techne-psm :refer :all])

(def rekb (create-rekb "Random rekb"))

(def node-0 (declare-atomic nil "Goal-0" :GOAL rekb))
(def node-1 (declare-atomic nil "Goal-1" :GOAL rekb))
(def node-2 (declare-atomic nil "Goal-2" :GOAL rekb))
(def node-3 (declare-atomic nil "Goal-3" :GOAL rekb))
(def node-4 (declare-atomic nil "Goal-4" :GOAL rekb))
(def node-5 (declare-atomic nil "Goal-5" :GOAL rekb))
(def node-6 (declare-atomic nil "Goal-6" :GOAL rekb))
(def node-7 (declare-atomic nil "Task-7" :TASK rekb))
(def node-8 (declare-atomic nil "Task-8" :TASK rekb))
(def node-9 (declare-atomic nil "Goal-9" :GOAL rekb))
(def node-10 (declare-atomic nil "Goal-10" :GOAL rekb))
(def node-11 (declare-atomic nil "Goal-11" :GOAL rekb))
(def node-12 (declare-atomic nil "Goal-12" :GOAL rekb))
(def node-13 (declare-atomic nil "Goal-13" :GOAL rekb))
(def node-14 (declare-atomic nil "Task-14" :TASK rekb))
(def node-15 (declare-atomic nil "Goal-15" :GOAL rekb))
(def node-16 (declare-atomic nil "Task-16" :TASK rekb))
(def node-17 (declare-atomic nil "Task-17" :TASK rekb))
(def node-18 (declare-atomic nil "Goal-18" :GOAL rekb))
(def node-19 (declare-atomic nil "Goal-19" :GOAL rekb))
(def node-20 (declare-atomic nil "Goal-20" :GOAL rekb))
(def node-21 (declare-atomic nil "Task-21" :TASK rekb))
(def node-22 (declare-atomic nil "Goal-22" :GOAL rekb))
(def node-23 (declare-atomic nil "Task-23" :TASK rekb))
(def node-24 (declare-atomic nil "Task-24" :TASK rekb))
(def node-25 (declare-atomic nil "Goal-25" :GOAL rekb))
(def node-26 (declare-atomic nil "Goal-26" :GOAL rekb))
(def node-27 (declare-atomic nil "Task-27" :TASK rekb))
(def node-28 (declare-atomic nil "Task-28" :TASK rekb))
(def node-29 (declare-atomic nil "Task-29" :TASK rekb))
(def node-30 (declare-atomic nil "Task-30" :TASK rekb))
(def node-31 (declare-atomic nil "Task-31" :TASK rekb))
(def node-32 (declare-atomic nil "Task-32" :TASK rekb))
(def node-33 (declare-atomic nil "Task-33" :TASK rekb))
(def node-34 (declare-atomic nil "Task-34" :TASK rekb))
(def node-35 (declare-atomic nil "Task-35" :TASK rekb))
(def node-36 (declare-atomic nil "Task-36" :TASK rekb))
(def node-37 (declare-atomic nil "Task-37" :TASK rekb))
(def node-38 (declare-atomic nil "Task-38" :TASK rekb))
(def node-39 (declare-atomic nil "Task-39" :TASK rekb))
(def node-40 (declare-atomic nil "Task-40" :TASK rekb))
(def node-41 (declare-atomic nil "Task-41" :TASK rekb))
(def node-42 (declare-atomic nil "Task-42" :TASK rekb))
(def node-43 (declare-atomic nil "Task-43" :TASK rekb))
(def node-44 (declare-atomic nil "Task-44" :TASK rekb))
(def node-45 (declare-atomic nil "Task-45" :TASK rekb))
(def node-46 (declare-atomic nil "Goal-46" :GOAL rekb))
(def node-47 (declare-atomic nil "Task-47" :TASK rekb))
(def node-48 (declare-atomic nil "Task-48" :TASK rekb))
(def node-49 (declare-atomic nil "Task-49" :TASK rekb))

(assrt-formula node-0 [node-1 node-2 node-40] :DA "phi-0-0" rekb)
(assrt-formula node-0 [node-9 node-11 node-12] :DA "phi-0-1" rekb)
(assrt-formula node-0 [node-48 node-19 node-28] :DA "phi-0-2" rekb)
(assrt-formula node-1 [node-32 node-3 node-4] :DA "phi-1-0" rekb)
(assrt-formula node-1 [node-5 node-6 node-7] :DA "phi-1-1" rekb)
(assrt-formula node-1 [node-8 node-9 node-42] :DA "phi-1-2" rekb)
(assrt-formula node-1 [node-39 node-22] :DA "phi-1-3" rekb)
(assrt-formula node-2 [node-6 node-3 node-36] :DA "phi-2-0" rekb)
(assrt-formula node-2 [node-45 node-30] :DA "phi-2-1" rekb)
(assrt-formula node-3 [node-25 node-15] :DA "phi-3-0" rekb)
(assrt-formula node-4 [node-16 node-27 node-36] :DA "phi-4-0" rekb)
(assrt-formula node-4 [node-37] :DA "phi-4-1" rekb)
(assrt-formula node-5 [node-42] :DA "phi-5-0" rekb)
(assrt-formula node-6 [node-24] :DA "phi-6-0" rekb)
(assrt-formula node-9 [node-10 node-45 node-47] :DA "phi-9-0" rekb)
(assrt-formula node-9 [node-48 node-17 node-18] :DA "phi-9-1" rekb)
(assrt-formula node-10 [node-21] :DA "phi-10-0" rekb)
(assrt-formula node-11 [node-18 node-20 node-30] :DA "phi-11-0" rekb)
(assrt-formula node-12 [node-35 node-13 node-15] :DA "phi-12-0" rekb)
(assrt-formula node-13 [node-44 node-38 node-14] :DA "phi-13-0" rekb)
(assrt-formula node-46 [node-49] :DA "phi-46-0" rekb)
(assrt-formula node-15 [node-43 node-21 node-46] :DA "phi-15-0" rekb)
(assrt-formula node-18 [node-41 node-23] :DA "phi-18-0" rekb)
(assrt-formula node-19 [node-34] :DA "phi-19-0" rekb)
(assrt-formula node-20 [node-24 node-33] :DA "phi-20-0" rekb)
(assrt-formula node-22 [node-26 node-27] :DA "phi-22-0" rekb)
(assrt-formula node-25 [node-33 node-29] :DA "phi-25-0" rekb)
(assrt-formula node-26 [node-31] :DA "phi-26-0" rekb)
(assrt-formula (contradiction rekb) [node-35 node-29] :DA "psi-0" rekb)
(assrt-formula (contradiction rekb) [node-24 node-12] :DA "psi-1" rekb)
(assrt-formula (contradiction rekb) [node-5 node-31] :DA "psi-2" rekb)
(assrt-formula (contradiction rekb) [node-33 node-42] :DA "psi-3" rekb)
(assrt-formula (contradiction rekb) [node-8 node-38] :DA "psi-4" rekb)
(assrt-formula (contradiction rekb) [node-2 node-30] :DA "psi-5" rekb)
(assrt-formula (contradiction rekb) [node-47 node-41] :DA "psi-6" rekb)
(assrt-formula (contradiction rekb) [node-40 node-9] :DA "psi-7" rekb)
(assrt-formula (contradiction rekb) [node-33 node-4] :DA "psi-8" rekb)
(assrt-formula (contradiction rekb) [node-40 node-12] :DA "psi-9" rekb)
