;; Leaves: 66-  Connectivity: %2.66666666667 Contradictions: 20
(require '[techne-psm :refer :all])

(def rekb (create-rekb "Random rekb"))

(def node-0 (declare-atomic nil "Goal-0" :GOAL rekb))
(def node-1 (declare-atomic nil "Goal-1" :GOAL rekb))
(def node-2 (declare-atomic nil "Goal-2" :GOAL rekb))
(def node-3 (declare-atomic nil "Goal-3" :GOAL rekb))
(def node-4 (declare-atomic nil "Task-4" :TASK rekb))
(def node-5 (declare-atomic nil "Goal-5" :GOAL rekb))
(def node-6 (declare-atomic nil "Goal-6" :GOAL rekb))
(def node-7 (declare-atomic nil "Task-7" :TASK rekb))
(def node-8 (declare-atomic nil "Goal-8" :GOAL rekb))
(def node-9 (declare-atomic nil "Goal-9" :GOAL rekb))
(def node-10 (declare-atomic nil "Task-10" :TASK rekb))
(def node-11 (declare-atomic nil "Task-11" :TASK rekb))
(def node-12 (declare-atomic nil "Task-12" :TASK rekb))
(def node-13 (declare-atomic nil "Task-13" :TASK rekb))
(def node-14 (declare-atomic nil "Goal-14" :GOAL rekb))
(def node-15 (declare-atomic nil "Task-15" :TASK rekb))
(def node-16 (declare-atomic nil "Goal-16" :GOAL rekb))
(def node-17 (declare-atomic nil "Goal-17" :GOAL rekb))
(def node-18 (declare-atomic nil "Goal-18" :GOAL rekb))
(def node-19 (declare-atomic nil "Goal-19" :GOAL rekb))
(def node-20 (declare-atomic nil "Goal-20" :GOAL rekb))
(def node-21 (declare-atomic nil "Task-21" :TASK rekb))
(def node-22 (declare-atomic nil "Task-22" :TASK rekb))
(def node-23 (declare-atomic nil "Task-23" :TASK rekb))
(def node-24 (declare-atomic nil "Goal-24" :GOAL rekb))
(def node-25 (declare-atomic nil "Goal-25" :GOAL rekb))
(def node-26 (declare-atomic nil "Task-26" :TASK rekb))
(def node-27 (declare-atomic nil "Goal-27" :GOAL rekb))
(def node-28 (declare-atomic nil "Task-28" :TASK rekb))
(def node-29 (declare-atomic nil "Task-29" :TASK rekb))
(def node-30 (declare-atomic nil "Goal-30" :GOAL rekb))
(def node-31 (declare-atomic nil "Goal-31" :GOAL rekb))
(def node-32 (declare-atomic nil "Task-32" :TASK rekb))
(def node-33 (declare-atomic nil "Goal-33" :GOAL rekb))
(def node-34 (declare-atomic nil "Task-34" :TASK rekb))
(def node-35 (declare-atomic nil "Goal-35" :GOAL rekb))
(def node-36 (declare-atomic nil "Task-36" :TASK rekb))
(def node-37 (declare-atomic nil "Goal-37" :GOAL rekb))
(def node-38 (declare-atomic nil "Task-38" :TASK rekb))
(def node-39 (declare-atomic nil "Goal-39" :GOAL rekb))
(def node-40 (declare-atomic nil "Goal-40" :GOAL rekb))
(def node-41 (declare-atomic nil "Task-41" :TASK rekb))
(def node-42 (declare-atomic nil "Task-42" :TASK rekb))
(def node-43 (declare-atomic nil "Task-43" :TASK rekb))
(def node-44 (declare-atomic nil "Task-44" :TASK rekb))
(def node-45 (declare-atomic nil "Goal-45" :GOAL rekb))
(def node-46 (declare-atomic nil "Task-46" :TASK rekb))
(def node-47 (declare-atomic nil "Task-47" :TASK rekb))
(def node-48 (declare-atomic nil "Task-48" :TASK rekb))
(def node-49 (declare-atomic nil "Task-49" :TASK rekb))
(def node-50 (declare-atomic nil "Task-50" :TASK rekb))
(def node-51 (declare-atomic nil "Task-51" :TASK rekb))
(def node-52 (declare-atomic nil "Task-52" :TASK rekb))
(def node-53 (declare-atomic nil "Task-53" :TASK rekb))
(def node-54 (declare-atomic nil "Task-54" :TASK rekb))
(def node-55 (declare-atomic nil "Task-55" :TASK rekb))
(def node-56 (declare-atomic nil "Goal-56" :GOAL rekb))
(def node-57 (declare-atomic nil "Goal-57" :GOAL rekb))
(def node-58 (declare-atomic nil "Goal-58" :GOAL rekb))
(def node-59 (declare-atomic nil "Task-59" :TASK rekb))
(def node-60 (declare-atomic nil "Task-60" :TASK rekb))
(def node-61 (declare-atomic nil "Task-61" :TASK rekb))
(def node-62 (declare-atomic nil "Goal-62" :GOAL rekb))
(def node-63 (declare-atomic nil "Task-63" :TASK rekb))
(def node-64 (declare-atomic nil "Task-64" :TASK rekb))
(def node-65 (declare-atomic nil "Goal-65" :GOAL rekb))
(def node-66 (declare-atomic nil "Task-66" :TASK rekb))
(def node-67 (declare-atomic nil "Task-67" :TASK rekb))
(def node-68 (declare-atomic nil "Task-68" :TASK rekb))
(def node-69 (declare-atomic nil "Goal-69" :GOAL rekb))
(def node-70 (declare-atomic nil "Task-70" :TASK rekb))
(def node-71 (declare-atomic nil "Task-71" :TASK rekb))
(def node-72 (declare-atomic nil "Task-72" :TASK rekb))
(def node-73 (declare-atomic nil "Task-73" :TASK rekb))
(def node-74 (declare-atomic nil "Task-74" :TASK rekb))
(def node-75 (declare-atomic nil "Task-75" :TASK rekb))
(def node-76 (declare-atomic nil "Task-76" :TASK rekb))
(def node-77 (declare-atomic nil "Task-77" :TASK rekb))
(def node-78 (declare-atomic nil "Task-78" :TASK rekb))
(def node-79 (declare-atomic nil "Task-79" :TASK rekb))
(def node-80 (declare-atomic nil "Task-80" :TASK rekb))
(def node-81 (declare-atomic nil "Task-81" :TASK rekb))
(def node-82 (declare-atomic nil "Goal-82" :GOAL rekb))
(def node-83 (declare-atomic nil "Task-83" :TASK rekb))
(def node-84 (declare-atomic nil "Goal-84" :GOAL rekb))
(def node-85 (declare-atomic nil "Task-85" :TASK rekb))
(def node-86 (declare-atomic nil "Task-86" :TASK rekb))
(def node-87 (declare-atomic nil "Task-87" :TASK rekb))
(def node-88 (declare-atomic nil "Task-88" :TASK rekb))
(def node-89 (declare-atomic nil "Goal-89" :GOAL rekb))
(def node-90 (declare-atomic nil "Task-90" :TASK rekb))
(def node-91 (declare-atomic nil "Task-91" :TASK rekb))
(def node-92 (declare-atomic nil "Task-92" :TASK rekb))
(def node-93 (declare-atomic nil "Task-93" :TASK rekb))
(def node-94 (declare-atomic nil "Task-94" :TASK rekb))
(def node-95 (declare-atomic nil "Task-95" :TASK rekb))
(def node-96 (declare-atomic nil "Task-96" :TASK rekb))
(def node-97 (declare-atomic nil "Task-97" :TASK rekb))
(def node-98 (declare-atomic nil "Task-98" :TASK rekb))
(def node-99 (declare-atomic nil "Task-99" :TASK rekb))

(assrt-formula node-0 [node-84 node-1 node-2] :DA "phi-0-0" rekb)
(assrt-formula node-0 [node-3 node-5 node-70] :DA "phi-0-1" rekb)
(assrt-formula node-0 [node-97 node-72 node-12] :DA "phi-0-2" rekb)
(assrt-formula node-0 [node-14 node-99 node-6] :DA "phi-0-3" rekb)
(assrt-formula node-0 [node-18 node-19 node-20] :DA "phi-0-4" rekb)
(assrt-formula node-0 [node-57 node-55 node-52] :DA "phi-0-5" rekb)
(assrt-formula node-0 [node-33 node-29 node-21] :DA "phi-0-6" rekb)
(assrt-formula node-1 [node-24 node-11 node-4] :DA "phi-1-0" rekb)
(assrt-formula node-1 [node-78 node-6] :DA "phi-1-1" rekb)
(assrt-formula node-2 [node-96 node-3 node-9] :DA "phi-2-0" rekb)
(assrt-formula node-2 [node-18 node-57 node-25] :DA "phi-2-1" rekb)
(assrt-formula node-2 [node-94 node-31] :DA "phi-2-2" rekb)
(assrt-formula node-3 [node-33 node-35 node-7] :DA "phi-3-0" rekb)
(assrt-formula node-3 [node-9 node-12 node-45] :DA "phi-3-1" rekb)
(assrt-formula node-3 [node-15] :DA "phi-3-2" rekb)
(assrt-formula node-5 [node-8 node-73 node-10] :DA "phi-5-0" rekb)
(assrt-formula node-5 [node-21 node-71] :DA "phi-5-1" rekb)
(assrt-formula node-6 [node-64 node-90 node-13] :DA "phi-6-0" rekb)
(assrt-formula node-6 [node-46] :DA "phi-6-1" rekb)
(assrt-formula node-8 [node-48 node-56 node-63] :DA "phi-8-0" rekb)
(assrt-formula node-8 [node-15] :DA "phi-8-1" rekb)
(assrt-formula node-9 [node-66 node-87 node-76] :DA "phi-9-0" rekb)
(assrt-formula node-9 [node-16 node-81 node-23] :DA "phi-9-1" rekb)
(assrt-formula node-9 [node-60 node-63] :DA "phi-9-2" rekb)
(assrt-formula node-14 [node-96 node-65 node-39] :DA "phi-14-0" rekb)
(assrt-formula node-14 [node-41 node-60 node-17] :DA "phi-14-1" rekb)
(assrt-formula node-14 [node-27 node-92] :DA "phi-14-2" rekb)
(assrt-formula node-16 [node-53] :DA "phi-16-0" rekb)
(assrt-formula node-17 [node-40 node-51 node-87] :DA "phi-17-0" rekb)
(assrt-formula node-18 [node-36 node-42 node-49] :DA "phi-18-0" rekb)
(assrt-formula node-18 [node-22 node-26 node-62] :DA "phi-18-1" rekb)
(assrt-formula node-19 [node-27 node-28] :DA "phi-19-0" rekb)
(assrt-formula node-20 [node-24 node-39 node-50] :DA "phi-20-0" rekb)
(assrt-formula node-20 [node-91 node-95] :DA "phi-20-1" rekb)
(assrt-formula node-24 [node-82 node-36 node-30] :DA "phi-24-0" rekb)
(assrt-formula node-25 [node-42 node-54] :DA "phi-25-0" rekb)
(assrt-formula node-27 [node-51 node-75 node-69] :DA "phi-27-0" rekb)
(assrt-formula node-27 [node-30 node-47] :DA "phi-27-1" rekb)
(assrt-formula node-30 [node-32] :DA "phi-30-0" rekb)
(assrt-formula node-31 [node-34 node-90] :DA "phi-31-0" rekb)
(assrt-formula node-33 [node-48 node-74 node-38] :DA "phi-33-0" rekb)
(assrt-formula node-35 [node-81 node-37] :DA "phi-35-0" rekb)
(assrt-formula node-37 [node-43 node-45 node-61] :DA "phi-37-0" rekb)
(assrt-formula node-39 [node-80 node-83 node-44] :DA "phi-39-0" rekb)
(assrt-formula node-40 [node-58 node-59 node-68] :DA "phi-40-0" rekb)
(assrt-formula node-40 [node-78 node-79] :DA "phi-40-1" rekb)
(assrt-formula node-45 [node-54] :DA "phi-45-0" rekb)
(assrt-formula node-56 [node-67 node-93] :DA "phi-56-0" rekb)
(assrt-formula node-57 [node-89 node-98] :DA "phi-57-0" rekb)
(assrt-formula node-58 [node-66 node-99 node-84] :DA "phi-58-0" rekb)
(assrt-formula node-62 [node-77] :DA "phi-62-0" rekb)
(assrt-formula node-65 [node-88 node-69] :DA "phi-65-0" rekb)
(assrt-formula node-69 [node-72 node-75] :DA "phi-69-0" rekb)
(assrt-formula node-82 [node-86] :DA "phi-82-0" rekb)
(assrt-formula node-84 [node-85] :DA "phi-84-0" rekb)
(assrt-formula node-89 [node-93] :DA "phi-89-0" rekb)
(assrt-formula (contradiction rekb) [node-92 node-19] :DA "psi-0" rekb)
(assrt-formula (contradiction rekb) [node-8 node-53] :DA "psi-1" rekb)
(assrt-formula (contradiction rekb) [node-24 node-12] :DA "psi-2" rekb)
(assrt-formula (contradiction rekb) [node-39 node-21] :DA "psi-3" rekb)
(assrt-formula (contradiction rekb) [node-39 node-10] :DA "psi-4" rekb)
(assrt-formula (contradiction rekb) [node-82 node-91] :DA "psi-5" rekb)
(assrt-formula (contradiction rekb) [node-59 node-86] :DA "psi-6" rekb)
(assrt-formula (contradiction rekb) [node-62 node-72] :DA "psi-7" rekb)
(assrt-formula (contradiction rekb) [node-1 node-87] :DA "psi-8" rekb)
(assrt-formula (contradiction rekb) [node-29 node-55] :DA "psi-9" rekb)
(assrt-formula (contradiction rekb) [node-95 node-51] :DA "psi-10" rekb)
(assrt-formula (contradiction rekb) [node-46 node-73] :DA "psi-11" rekb)
(assrt-formula (contradiction rekb) [node-35 node-73] :DA "psi-12" rekb)
(assrt-formula (contradiction rekb) [node-8 node-52] :DA "psi-13" rekb)
(assrt-formula (contradiction rekb) [node-15 node-22] :DA "psi-14" rekb)
(assrt-formula (contradiction rekb) [node-51 node-70] :DA "psi-15" rekb)
(assrt-formula (contradiction rekb) [node-15 node-77] :DA "psi-16" rekb)
(assrt-formula (contradiction rekb) [node-30 node-47] :DA "psi-17" rekb)
(assrt-formula (contradiction rekb) [node-32 node-61] :DA "psi-18" rekb)
(assrt-formula (contradiction rekb) [node-54 node-97] :DA "psi-19" rekb)
